# port of the http server
port: 9281 
# port of the https server
sslport: 0
# this is the servicURL from outside
serviceURL: http://127.0.0.1:9281
healthcheck:
    period: 30
logging:
    level: info
    filename: ${configdir}/logging.log