name: Default
description: This is the default profile
pages:
    - name: Default
      description: This is the default page
      columns: 3
      rows: 5
      toolbar: ""
      cells: []
actions: []
