port: 9280
sslport: 0
serviceURL: http://127.0.0.1:9280
secretfile: ""
password: "akteon00"
appid: 73
appuuid: dev_system
healthcheck:
    period: 30
profiles: ./devdata/profiles
sessions: ./devdata/sessions
timezonezip: ./devdata/zoneinfo.zip
extconfig:
    audioplayer:
        active: false
        samplerate: 48kHz
    homematic:
        active: false
        updateperiod: 5
        url: http://192.168.178.80
    obs:
        active: false
        host: 127.0.0.1
        password: akteon00
        port: 4444
    openhardwaremonitor:
        active: false
        updateperiod: 5
        url: http://127.0.0.1:12999/data.json
    philipshue:
        active: false
        device: recos#hue_user
        ipaddress: 192.168.178.81
        updateperiod: 5
        username: IwtURJmST8b44mvZSZ2nl73nZhghVltMvgzlH7UC
    streamdeck:
        active: false
        profile: streamdeck
        program: C:/e-platte/daten/git-sourcen/ReCoS-Remote-Command-Service/integrations/streamdeck/StreamDeckService/bin/Release/net5.0-windows/publish
logging:
    level: debug
    filename: ./devdata/logging.log
