port: 9280
sslport: 0
serviceURL: http://127.0.0.1:9280
secretfile: ""
password: ""
appid: 0
appuuid: dev_system
webclient: ../webclient/RecosUI/dist
adminclient: ../webclient/recosadmin/dist
icons: ../general/assets
healthcheck:
    period: 30
profiles: ./devdata/profiles
sessions: ./devdata/sessions
timezonezip: ./devdata/zoneinfo.zip
extconfig:
    openhardwaremonitor:
        updateperiod: 5
        url: http://127.0.0.1:12999/data.json
    audioplayer:
        samplerate: 48000
    philipshue:
        username: IwtURJmST8b44mvZSZ2nl73nZhghVltMvgzlH7UC
        device: recos#hue_user
        ipaddress: 192.168.178.81
logging:
    level: debug
    filename: ./devdata/logging.log
