openapi: 3.0.0
info:
  title: ReCoS API
  description: This is the ReCoS Client API, indendet for every client to connect. 
  contact:
    email: w.klaas@gmx.de
    name: Wilfried Klaas
    url: wk-music.de
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.0
servers:
  - url: http://127.0.0.1:9280/api/v1
    description: This is the local endpoint to the client api
paths:
  /config/icons:
    get:
      summary: returns a list of all possilbe icon names
      responses:
        200:
          description: a json array with all names of all possible client icons
          content:
            application/json:
              schema: 
                type: array
                items: 
                  type: string
  /show:
    get:
      summary: returns a list of all active profiles with name and description
      responses:
        200:
          description: a json array with all names and desscription of all active profiles
          content:
            application/json:
              schema: 
                type: array
                items:
                  $ref: "#/components/schemas/ProfileInfo"
  /show/{profileid}:
    get:
      summary: returns the definition of the profile
      parameters:
        - name: profileid
          in: path
          required: true
          description: The id of the profile to retrieve
          schema:
            type: string
      responses:
        200:
          description: a json object with the definition of the profiles
          content:
            application/json:
              schema: 
                $ref: "#/components/schemas/Profile"
                  
components:
  schemas: 
    ProfileInfo:
      type: object
      required: 
        - name
      properties:
        name:
          type: string
          example: default
        description: 
          type: string
    Profile:
      type: object
      required: 
        - name
        - pages
      properties:
        name:
          type: string
          example: default
        description: 
          type: string
        pages:
          type: array
          items: 
            $ref: "#/components/schemas/Page"
        actions:
          type: array
          items:
            $ref: "#/components/schemas/Action"
    Page:
      type: object
      required:
        - name
      properties:
        name:
          type: string
        description:
          type: string
        icon: 
          type: string
        columns:
          type: integer
        rows: 
          type: integer
        toolbar:
          type: string
          enum:
            - show
            - hide
        cells:
          type: array
          items:
            type: string
    Action:
      type: object
      required:
        - type
        - name
      properties:
        type: 
          type: string
          enum:
            - SINGLE
            - DISPLAY
            - TOGGLE
            - MULTI
        name:
          type: string
        title:
          type: string
        description:
          type: string
        icon: 
          type: string
        fontsize:
          type: integer
        fontcolor:
          type: string
        outlined:
          type: boolean
