name: Default
description: This is the default configuration, just to have one starting point
pages:
  - name: Default
    description: Some default command for every operating system
    columns: 5
    rows: 3
    cells:
      - delay1
      - delay2
      - sendkeys
      - noop
      - timer
      - timer2
      - clocks
      - clock
      - analogclock
      - cputemp
      - cpuload
      - stopwatch
      - noop1
      - 
  - name: clocks
    description: clocks only
    columns: 3
    rows: 3
    toolbar: hide
    cells:
      - page1
      - none
      - none
      - none
      - clock
      - analogclock
  - name: hardware
    description: hardware statistics only
    columns: 3
    rows: 3
    cells:
      - cputemp
      - cpuload
  - name: windows
    description: only working on windows
    columns: 3
    rows: 3
    cells:
      - window_ctrl
      - execgo
actions:
  - type: SINGLE
    name: delay1
    title: short delay
    description: Just a short delay
    icon: hourglass_begin.png
    fontsize: 10
    fontcolor: "#FF0000"
    outlined: true
    runone: true
    commands:
      - type: DELAY
        name: delay
        parameters:
          time: 2
  - type: SINGLE
    name: delay2
    title: Pause
    description: Stepped Delay with different titles
    runone: false
    commands:
      - type: DELAY
        name: delay
        icon: address_book.png
        title: step 1
        parameters:
          time: 1
      - type: DELAY
        name: delay
        title: step 2
        parameters:
          time: 1
      - type: DELAY
        name: delay
        title: step 3
        parameters:
          time: 1
      - type: DELAY
        name: delay
        title: step 4
        parameters:
          time: 1
      - type: DELAY
        name: delay
        title: step 5
        parameters:
          time: 1
      - type: DELAY
        name: delay
        title: step 6
        parameters:
          time: 1
      - type: DELAY
        name: delay
        title: step 7
        parameters:
          time: 1
      - type: DELAY
        name: delay
        title: step 8
        parameters:
          time: 1
      - type: DELAY
        name: delay
        title: step 9
        parameters:
          time: 1
      - type: DELAY
        name: delay
        title: step 10
        parameters:
          time: 1
      - type: DELAY
        name: delay
        title: step 11
        parameters:
          time: 1
      - type: DELAY
        name: delay
        title: step 12
        parameters:
          time: 1
  - type: SINGLE
    name: execgo
    title: go version
    description: Execute go version 
    runone: true
    commands:
      - type: EXECUTE
        name: execute
        parameters:
          command: go.exe
          args:
            - "version"
  - type: SINGLE
    name: clocks
    title: Clocks
    description: Goto clocks page
    runone: true
    commands:
      - type: PAGE
        name: page
        parameters:
          page: clocks
  - type: SINGLE
    name: page1
    title: Back
    description: Goto default page
    icon: arrow_left.png
    runone: true
    commands:
      - type: PAGE
        name: page
        parameters:
          page: Default
  - type: SINGLE
    name: sendkeys
    title: Sending some keys
    description: description for page
    runone: true
    commands:
      - type: DELAY
        name: delay
        parameters:
          time: 5
      - type: KEYS
        name: sendkeys
        parameters:
          layout: de
          keys: "{esc}1+1{enter}"
  - type: SINGLE
    name: window_ctrl
    title: window_ctrl
    description: window_ctrl
    runone: true
    commands:
      - type: DELAY
        name: delay1
        parameters:
          time: 2
      - type: WINDOWCTRL
        name: control window
        parameters:
          caption: Rechner 
          command: activate
      - type: DELAY
        name: delay2
        parameters:
          time: 1
      - type: KEYS
        name: sendkeys
        parameters:
          layout: de
          keys: "{esc}1+1{enter}"
      - type: DELAY
        name: delay3
        parameters:
          time: 2
      - type: WINDOWCTRL
        name: control window
        parameters:
          caption: Rechner 
          command: move 700 300 
      - type: DELAY
        name: delay4
        parameters:
          time: 2
      - type: WINDOWCTRL
        name: control window
        parameters:
          caption: Rechner 
          command: minimize
  - type: SINGLE
    name: noop
    title: Do nothing
    description: do nothing
    icon: light_bulb.png
    runone: true
    commands:
      - type: NOOP
        name: noop
        title: Waiting
  - type: SINGLE
    name: timer
    title: Timer 10 sec
    description: timer counting down 10 sec
    icon: alarm_bell.png
    runone: true
    commands:
      - type: TIMER
        name: timer
        parameters:
          time: 10
          format: noch %ds
          finished: Fertig
  - type: SINGLE
    name: timer2
    title: Timer 20 sec
    description: timer counting down 20 sec
    icon: time_frame.png
    runone: true
    commands:
      - type: TIMER
        name: timer
        parameters:
          time: 20
          format: "%d Sekunden"
  - type: DISPLAY
    name: clock
    title: Clock
    runone: true
    outlined: false
    fontcolor: white
    commands:
      - type: CLOCK
        name: clock
        parameters:
          format: "15:04:05\r\n02 Jan 06"
          analog: false
  - type: DISPLAY
    name: analogclock
    title: Analogclock
    runone: true
    outlined: false
    fontcolor: white
    commands:
      - type: CLOCK
        name: clock
        parameters:
          format: "15:04:05\r\n02 Jan 06"
          analog: true
  - type: SINGLE
    name: screenshot
    title: Screenshot
    description: doing a screenshot
    icon: monitor.png
    runone: true
    commands:
      - type: SCREENSHOT
        name: screenshot
        parameters:
          saveto: e:/temp/screenshot
          display: 1
  - type: DISPLAY
    name: cputemp
    title: CPU Temp
    description: cpu temp
    runone: true
    icon: company.png
    outlined: true
    commands:
      - type: HARDWAREMONITOR
        name: cpu
        parameters:
          sensor: "CPU/Intel Core i7-6820HQ/Temperature/CPU Package"
          format: "%0.1f °C"
          display: both
          ymin: 30
          ymax: 80
          color: "#00ff00"
  - type: DISPLAY
    name: cpuload
    title: CPU Load
    description: cpu usage
    runone: true
    icon: company.png
    outlined: false
    fontcolor: white
    commands:
      - type: HARDWAREMONITOR
        name: cpu
        parameters:
          sensor: "CPU/Intel Core i7-6820HQ/Load/CPU Total"
          format: "%0.1f %"
          display: both
          color: "#ffff00"
  - type: SINGLE
    name: stopwatch
    title: Stopwatch
    description: simple stop watch
    icon: timer.png
    runone: true
    outlined: true
    fontcolor: black
    commands:
      - type: STOPWATCH
        name: stp1
        parameters:
          format: "Mom: %0m:%0s"
        